club/urls.py
from django.urls import path
from . import views

app_name = 'club'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('about_detail/<int:id>', views.about_detail_def, name="about_detail_url"),

    path('member_list', views.MemberListView.as_view(), name="member_list_url"),
    path('member_detail/<int:id>', views.member_detail_def, name="member_detail_url"),

    path('field_list', views.FieldListView.as_view(), name="field_list_url"),
    path('field_detail/<int:id>', views.field_detail_def, name="field_detail_url"),

]

gym/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from club import views

urlpatterns = [
    url('admin/', admin.site.urls),
    path('club/', include('club.urls')),
    path('store/', include('store.urls')),
    path('contact/', views.tell_me_view, name="contact"),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('product_list/', views.ProductLisView.as_view(), name="product_list_url"),
    path('product_detail/<int:id>', views.product_detail_def, name="product_detail_url"),

    path('payment_list/', views.PaymentListView.as_view(), name="payment_list_url"),
    path('payment_detail/<int:id>', views.payment_detail_def, name="payment_detail_url"),

    path('shop/', views.shopping_form_view, name="shopping_form_url"),

]

templates/about_detail.html
{% extends "base.html" %}

{% block link %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock %}

{% block title%} About Detail {% endblock %}

{% block content %}
<h1>This is Detail View Page</h1>
{% for title in object_list %}
    <ul>
        <li><a href="#">{{ title.name }}</a></li>
    </ul>
    <hr>
    <h3>Description Of About '{{title.name}}':</h3>
    <p>{{title.description}}</p>
{% endfor %}
{% endblock %}

templates/about_list.html
{% extends "base.html" %}

{% block link %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css'%}">
{% endblock %}

{% block title%} About List {% endblock %}

{% block content %}
<h1>About List</h1>
<ul>
    {% for about in object_list %}
    <li>
        <a href=" {% url 'club:about_detail_url' about.pk %} ">
            {{ about.name }}
        </a>
        <br>
    </li>
    {% empty %}
    <li>No articles yet.</li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js//bootstrap.min.js"></script>

    {% block link %} {% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'club/css/style.css' %}">

    <title>{% block title %} {% endblock %}</title>

</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">

                <li><a href="{% url 'club:index' %}">Home</a></li>

                <li><a href="{% url 'contact' %}"><span class="glyphicon glyphicon-plus">Tell me</span></a></li>


                <li><a href="{% url 'club:member_list_url' %}">Member</a></li>
                <li><a href="{% url 'club:field_list_url' %}">Field</a></li>

                <li><a href="{% url 'store:product_list_url' %}">Product</a></li>
                <li><a href="{% url 'store:payment_list_url' %}">Payment</a></li>

                <li><a href="admin/">Admin</a></li>
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %} {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block link %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %} تماس با ما {% endblock %}

{% block content %}
<form method="post">
    {% csrf_token  %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">save</button>
</form>

{% endblock %}